### ISSUE TITLE
Advice for applying to high-dimensional data

### ISSUE THREAD

**Issue by SultanOrazbayev** [mchalela/GriSPy#15]
Hello,

I am experimenting with your module on high-dimensional data, so I modified the tutorial code, but the kernel keeps crashing when I try to use k=8 or more. Here's the code I am running (it's almost identical to the tutorial code):

```python
import numpy as np
import matplotlib.pyplot as plt

from grispy import GriSPy as G

Npoints = 10 ** 1
Ncentres = 2
dim = 8
Lbox = 100.0

np.random.seed(0)
data = np.random.uniform(0, Lbox, size=(Npoints, dim))
centres = np.random.uniform(0, Lbox, size=(Ncentres, dim))

periodic = {n: (0, Lbox) for n in range(dim)}
gsp = G(data, periodic=periodic)
upper_radii = 10.0

# the kernel crashes when executing the following line
bubble_dist, bubble_ind = gsp.bubble_neighbors(
    centres, distance_upper_bound=upper_radii
)
```

Perhaps I am doing something wrong, so could you advise how/whether I can apply this to high-dimensional data, where k is on the scale of 10'000?

**Comment by SultanOrazbayev** [comment]
Also, the same happens without periodic boundaries.

**Comment by SultanOrazbayev** [comment]
And if it helps the 10'000 features are sparse (so very few elements are non-zero).

**Comment by SultanOrazbayev** [comment]
Sorry for multiple posts. I understand now where the issue arises (grid is N_cells ** k , which places upper limit on k). So one way to increase k is to reduce N_cells to just 2 (which is probably fine for binary features). However, that still means it's not possible to go beyond 30 features or so (2**32).

**Comment by mchalela** [comment]
Hi @SultanOrazbayev, indeed you are facing a limitation in Grispy's code. As you mentioned the total number of cells increases as N_cell**k, so even for small N_cells (~2) you probably can't increase beyond 30 or so dimensions. At this point you will quickly run out of RAM and probably crash your system. 

The main problem here is that Grispy was optimized to achieve the best time performance possible, sacrificing the memory usage. As a general rule, when you optimize one of those resources (time or memory) is at the expense of the other. Because of this, Grispy performs better when dealing with a relatively low number of dimensions. Unfortunately, if you need to work with k~10000 Grispy is not a viable solution to your particular problem.

**Comment by SultanOrazbayev** [comment]
Thank you, @mchalela !
