### ISSUE TITLE
indexing large data

### ISSUE THREAD

**Issue by SultanOrazbayev** [mchalela/GriSPy#6]
Hello, thank you for this interesting work!

I wonder if there is a way to index large data in advance and store it in a file? (I guess pickling is one option)

**Comment by mchalela** [comment]
Hello! Thank you for your interest!
There used to be save and load methods that pickled the Grispy instance. However, it turned out to be faster to create the grid again than unpickling it from a file. That version was very preliminary and the time benchmark we did was not very exhaustive. I definitively think there has to be a better way to do this. We'll give it a thought for the next release and I'll come back to you on this.

**Comment by SultanOrazbayev** [comment]
Thank you for the quick response!

**Comment by mchalela** [comment]
We couldn't come up with a save/load implementation that was faster than creating the grid every time.
